import type {
  AssessmentQuestion,
  Career,
  ProjectRec,
  StudentProfile,
  Degree,
  Branch,
  SkillLevel,
} from "./types";

export const DEGREES: Degree[] = [
  "B.Tech",
  "B.E.",
  "BCA",
  "B.Sc",
  "BBA",
  "B.Com",
  "BA",
  "Other",
];

export const BRANCHES: Branch[] = [
  "CSE",
  "AIML",
  "Data Science",
  "IT",
  "ECE",
  "EEE",
  "Mechanical",
  "Civil",
  "Chemical",
  "Biotechnology",
  "Automobile",
  "Aerospace",
  "Biomedical",
  "Mechatronics",
  "Robotics",
  "Other",
];

export const INTEREST_AREAS = [
  "Software & Coding",
  "Data & Analytics",
  "AI & Machine Learning",
  "Hardware & Electronics",
  "Design & UX",
  "Business & Management",
  "Finance & Fintech",
  "Marketing & Content",
  "Core Engineering",
  "Healthcare & Biology",
  "Research",
  "Entrepreneurship",
  "Teaching & Training",
  "Civil Services & Policy",
] as const;

export type InterestArea = (typeof INTEREST_AREAS)[number];

/** Master skill list used across onboarding, profile and matching */
export const CORE_SKILLS = [
  "Python",
  "Java",
  "C / Embedded C",
  "JavaScript",
  "Web Development",
  "DSA",
  "SQL",
  "Excel & Sheets",
  "Statistics",
  "Machine Learning",
  "Deep Learning",
  "LLM APIs & RAG",
  "Prompt Engineering",
  "Data Visualization",
  "Microcontrollers",
  "Circuit Design",
  "CAD (SolidWorks/CATIA)",
  "FEA / Simulation",
  "Structural Analysis",
  "STAAD Pro / ETABS",
  "Molecular Biology",
  "Lab Techniques",
  "Bioinformatics Tools",
  "Financial Accounting",
  "Business Domain",
  "HR Fundamentals",
  "SEO & Content",
  "Social Media",
  "Copywriting",
  "Marketing Analytics",
  "Figma & Design Tools",
  "User Research",
  "Prototyping",
  "Git & GitHub",
  "Docker & Cloud",
  "Communication",
  "Financial Modeling",
  "Vector Databases",
  "Engineering Drawing",
  "Manufacturing Processes",
];

export const CAREERS: Career[] = [
  {
    id: "ml-engineer",
    title: "Machine Learning Engineer",
    family: "AI & Data",
    tagline: "Build and deploy models that power real products.",
    degrees: ["B.Tech", "B.E.", "BCA", "B.Sc"],
    branches: ["CSE", "AIML", "Data Science", "IT", "ECE"],
    openToAllBranches: true,
    demand: "Very High",
    avgSalaryLPA: "8–25 LPA",
    requiredSkills: [
      { name: "Python", weight: 3, level: 4 },
      { name: "Statistics", weight: 2, level: 3 },
      { name: "Machine Learning", weight: 3, level: 4 },
      { name: "Deep Learning", weight: 2, level: 3 },
      { name: "SQL", weight: 2, level: 3 },
      { name: "Docker & Cloud", weight: 1, level: 3 },
      { name: "DSA", weight: 1, level: 3 },
    ],
    interests: ["AI & Machine Learning", "Data & Analytics", "Software & Coding"],
    projects: ["ml-endtoend", "nlp-sentiment", "cv-defect"],
    whyTemplate:
      "Strong match with your {interest} interest and your {branch} background; Python + ML is the core stack here.",
    roadmap: [
      {
        id: "rm-ml-1",
        title: "Python Foundations",
        duration: "4 weeks",
        goals: ["Write clean, idiomatic Python", "Comfort with data structures"],
        tasks: [
          "Complete a Python fundamentals course",
          "Solve 30 easy exercises",
          "Learn NumPy & Pandas basics",
        ],
        projects: ["Data cleaning notebook on a public dataset"],
      },
      {
        id: "rm-ml-2",
        title: "Maths for ML",
        duration: "3 weeks",
        goals: ["Linear algebra intuition", "Probability & statistics core"],
        tasks: [
          "Vectors, matrices, dot products",
          "Distributions, hypothesis testing",
          "Descriptive vs inferential statistics",
        ],
        projects: ["A/B test analysis report"],
      },
      {
        id: "rm-ml-3",
        title: "Machine Learning Core",
        duration: "6 weeks",
        goals: ["Train & evaluate classical models", "Feature engineering"],
        tasks: [
          "Regression, classification, clustering",
          "Cross-validation & metrics",
          "Scikit-learn pipelines",
        ],
        projects: ["ml-endtoend"],
      },
      {
        id: "rm-ml-4",
        title: "Deep Learning",
        duration: "5 weeks",
        goals: ["Neural networks from scratch to frameworks"],
        tasks: [
          "Backpropagation intuition",
          "CNNs for images, RNNs/transformers for text",
          "PyTorch basics",
        ],
        projects: ["nlp-sentiment"],
      },
      {
        id: "rm-ml-5",
        title: "MLOps & Deployment",
        duration: "4 weeks",
        goals: ["Ship a model as an API", "Version & monitor models"],
        tasks: [
          "FastAPI + Docker deployment",
          "Experiment tracking (MLflow)",
          "Basic cloud (AWS/GCP free tier)",
        ],
        projects: ["Deploy rm-ml-3 model with FastAPI + Docker"],
      },
      {
        id: "rm-ml-6",
        title: "Internship & Placement Prep",
        duration: "4 weeks",
        goals: ["Portfolio polish + interview readiness"],
        tasks: [
          "GitHub profile & README polish",
          "Resume tailored to ML roles",
          "150 DSA problems + ML interview questions",
        ],
        projects: ["Capstone: end-to-end ML product"],
      },
    ],
  },
  {
    id: "data-scientist",
    title: "Data Scientist",
    family: "AI & Data",
    tagline: "Turn messy data into decisions and stories.",
    degrees: ["B.Tech", "B.E.", "BCA", "B.Sc", "B.Com", "BBA"],
    branches: ["CSE", "AIML", "Data Science", "IT", "ECE", "Other"],
    openToAllBranches: true,
    demand: "Very High",
    avgSalaryLPA: "7–22 LPA",
    requiredSkills: [
      { name: "Python", weight: 3, level: 4 },
      { name: "SQL", weight: 3, level: 4 },
      { name: "Statistics", weight: 3, level: 4 },
      { name: "Machine Learning", weight: 2, level: 3 },
      { name: "Data Visualization", weight: 2, level: 3 },
      { name: "Business Domain", weight: 1, level: 3 },
    ],
    interests: ["Data & Analytics", "AI & Machine Learning", "Business & Management"],
    projects: ["sales-forecast", "ab-test-suite", "covid-dashboard"],
    whyTemplate:
      "Your {interest} interest plus SQL/Python skills fit the analytics-first nature of this role.",
    roadmap: [
      {
        id: "rm-ds-1",
        title: "Spreadsheets to SQL",
        duration: "4 weeks",
        goals: ["Query real databases confidently"],
        tasks: ["SELECT to JOINs", "Window functions", "Practice on 50 SQL problems"],
        projects: ["Retail sales SQL analysis"],
      },
      {
        id: "rm-ds-2",
        title: "Python Data Stack",
        duration: "4 weeks",
        goals: ["Pandas mastery", "Clean, transform, merge data"],
        tasks: ["Pandas deep dive", "Matplotlib/Seaborn", "Data storytelling basics"],
        projects: ["covid-dashboard"],
      },
      {
        id: "rm-ds-3",
        title: "Statistics & Experimentation",
        duration: "4 weeks",
        goals: ["Think in probabilities and tests"],
        tasks: ["Distributions & CLT", "A/B testing framework", "Regression analysis"],
        projects: ["ab-test-suite"],
      },
      {
        id: "rm-ds-4",
        title: "Machine Learning for Data Science",
        duration: "5 weeks",
        goals: ["Applied modeling, not research"],
        tasks: ["Supervised learning workflow", "Feature engineering", "Model evaluation & business metrics"],
        projects: ["sales-forecast"],
      },
      {
        id: "rm-ds-5",
        title: "Portfolio & Communication",
        duration: "3 weeks",
        goals: ["Tell stories with data"],
        tasks: ["3 polished case studies", "Tableau/Power BI dashboard", "Blog/writeup for each project"],
        projects: ["End-to-end case study with business recommendations"],
      },
    ],
  },
  {
    id: "ai-engineer",
    title: "AI Engineer (GenAI / LLM)",
    family: "AI & Data",
    tagline: "Build products on top of LLMs and modern AI APIs.",
    degrees: ["B.Tech", "B.E.", "BCA", "B.Sc"],
    branches: ["CSE", "AIML", "Data Science", "IT", "ECE"],
    openToAllBranches: true,
    demand: "High",
    avgSalaryLPA: "9–28 LPA",
    requiredSkills: [
      { name: "Python", weight: 3, level: 4 },
      { name: "Prompt Engineering", weight: 2, level: 4 },
      { name: "LLM APIs & RAG", weight: 3, level: 4 },
      { name: "Web Development", weight: 2, level: 3 },
      { name: "Docker & Cloud", weight: 1, level: 3 },
      { name: "Vector Databases", weight: 1, level: 3 },
    ],
    interests: ["AI & Machine Learning", "Software & Coding", "Entrepreneurship"],
    projects: ["rag-tutor", "career-agent"],
    whyTemplate:
      "The fastest-growing AI product role; pairs your {interest} interest with hands-on building.",
    roadmap: [
      {
        id: "rm-ai-1",
        title: "Python + APIs",
        duration: "3 weeks",
        goals: ["Call any API confidently", "Async Python"],
        tasks: ["HTTP, JSON, auth", "FastAPI service", "Error handling & retries"],
        projects: ["Weather + news aggregator bot"],
      },
      {
        id: "rm-ai-2",
        title: "LLM Foundations",
        duration: "3 weeks",
        goals: ["Prompting & token economics"],
        tasks: ["Prompt patterns", "Structured outputs (JSON mode)", "Cost/latency tradeoffs"],
        projects: ["Prompt library with eval harness"],
      },
      {
        id: "rm-ai-3",
        title: "RAG & Agents",
        duration: "5 weeks",
        goals: ["Ground LLMs in private data"],
        tasks: ["Embeddings & vector DBs", "Chunking & retrieval strategies", "Tool-calling agents"],
        projects: ["rag-tutor"],
      },
      {
        id: "rm-ai-4",
        title: "Full-Stack AI Product",
        duration: "5 weeks",
        goals: ["Ship a usable AI product"],
        tasks: ["Next.js or React frontend", "Auth + DB basics", "Deploy with Docker"],
        projects: ["career-agent"],
      },
      {
        id: "rm-ai-5",
        title: "Portfolio & Internship Hunt",
        duration: "3 weeks",
        goals: ["Stand out with shipped products"],
        tasks: ["Demo videos for projects", "Technical blog posts", "Apply with tailored resume"],
        projects: ["Polish rag-tutor into a portfolio centerpiece"],
      },
    ],
  },
  {
    id: "fullstack-dev",
    title: "Full-Stack Developer",
    family: "Software",
    tagline: "Design, build and ship complete web products.",
    degrees: ["B.Tech", "B.E.", "BCA", "B.Sc"],
    branches: ["CSE", "IT", "AIML", "Data Science", "ECE"],
    openToAllBranches: true,
    demand: "High",
    avgSalaryLPA: "6–20 LPA",
    requiredSkills: [
      { name: "JavaScript", weight: 3, level: 4 },
      { name: "Web Development", weight: 3, level: 4 },
      { name: "Databases & SQL", weight: 2, level: 3 },
      { name: "DSA", weight: 2, level: 3 },
      { name: "Git & GitHub", weight: 2, level: 3 },
      { name: "Docker & Cloud", weight: 1, level: 2 },
    ],
    interests: ["Software & Coding", "Entrepreneurship", "Design & UX"],
    projects: ["saas-dashboard", "ecommerce-api", "career-agent"],
    whyTemplate:
      "Your {interest} interest maps directly to product building; strong hiring volume across IT services and startups.",
    roadmap: [
      {
        id: "rm-fs-1",
        title: "Web Fundamentals",
        duration: "4 weeks",
        goals: ["HTML/CSS/JS fluency"],
        tasks: ["Flexbox & Grid", "DOM & events", "Build 3 static pages pixel-perfect"],
        projects: ["Personal portfolio site"],
      },
      {
        id: "rm-fs-2",
        title: "Frontend Framework",
        duration: "5 weeks",
        goals: ["Component thinking with React"],
        tasks: ["React + hooks", "State management", "API integration"],
        projects: ["Movie search app with API"],
      },
      {
        id: "rm-fs-3",
        title: "Backend & Databases",
        duration: "5 weeks",
        goals: ["Build REST APIs", "Model data well"],
        tasks: ["Node/Express or Next.js API routes", "PostgreSQL/MongoDB", "Auth (JWT/sessions)"],
        projects: ["ecommerce-api"],
      },
      {
        id: "rm-fs-4",
        title: "Full-Stack Product",
        duration: "6 weeks",
        goals: ["End-to-end ownership"],
        tasks: ["Integrate frontend + backend", "Deployment (Vercel/Render)", "Testing basics"],
        projects: ["saas-dashboard"],
      },
      {
        id: "rm-fs-5",
        title: "DSA + Placement",
        duration: "6 weeks",
        goals: ["Crack technical interviews"],
        tasks: ["150-200 DSA problems", "System design basics", "Mock interviews"],
        projects: ["Open-source contribution"],
      },
    ],
  },
  {
    id: "data-analyst",
    title: "Data / Business Analyst",
    family: "AI & Data",
    tagline: "Dashboards, reports and insights that drive business.",
    degrees: ["B.Tech", "B.E.", "BCA", "B.Sc", "BBA", "B.Com", "BA"],
    branches: ["CSE", "IT", "AIML", "Data Science", "Other"],
    openToAllBranches: true,
    demand: "High",
    avgSalaryLPA: "5–14 LPA",
    requiredSkills: [
      { name: "SQL", weight: 3, level: 4 },
      { name: "Excel & Sheets", weight: 2, level: 4 },
      { name: "Data Visualization", weight: 3, level: 4 },
      { name: "Python", weight: 2, level: 3 },
      { name: "Business Domain", weight: 2, level: 3 },
      { name: "Statistics", weight: 1, level: 3 },
    ],
    interests: ["Data & Analytics", "Business & Management", "Finance & Fintech"],
    projects: ["covid-dashboard", "sales-forecast", "hr-analytics"],
    whyTemplate:
      "Open to every degree; your {interest} interest and reporting strengths fit this analytics role.",
    roadmap: [
      {
        id: "rm-ba-1",
        title: "Excel & SQL",
        duration: "3 weeks",
        goals: ["Everyday analyst toolkit"],
        tasks: ["Pivot tables, VLOOKUP/XLOOKUP", "SQL joins & aggregations", "Data cleaning drills"],
        projects: ["Sales dataset cleanup + pivot report"],
      },
      {
        id: "rm-ba-2",
        title: "Visualization",
        duration: "3 weeks",
        goals: ["Build dashboards people use"],
        tasks: ["Power BI or Tableau", "Chart selection & storytelling", "KPI design"],
        projects: ["covid-dashboard"],
      },
      {
        id: "rm-ba-3",
        title: "Python for Analysis",
        duration: "4 weeks",
        goals: ["Go beyond spreadsheets"],
        tasks: ["Pandas", "Basic statistics", "Automated reporting"],
        projects: ["hr-analytics"],
      },
      {
        id: "rm-ba-4",
        title: "Business Domain + Case Studies",
        duration: "4 weeks",
        goals: ["Analyst thinking"],
        tasks: ["Pick a domain (retail/finance/HR)", "3 case studies with recommendations", "Stakeholder-style presentations"],
        projects: ["Full business analysis case study"],
      },
    ],
  },
  {
    id: "digital-marketer",
    title: "Digital Marketing / Growth",
    family: "Business",
    tagline: "Grow products with content, ads and analytics.",
    degrees: ["BBA", "B.Com", "BA", "B.Sc", "B.Tech", "BCA"],
    branches: ["Other", "CSE", "IT", "Mechanical", "Civil"],
    openToAllBranches: true,
    demand: "Growing",
    avgSalaryLPA: "4–12 LPA",
    requiredSkills: [
      { name: "SEO & Content", weight: 3, level: 4 },
      { name: "Marketing Analytics", weight: 2, level: 3 },
      { name: "Social Media", weight: 2, level: 3 },
      { name: "Copywriting", weight: 2, level: 3 },
      { name: "Excel & Sheets", weight: 1, level: 3 },
      { name: "AI Tools", weight: 1, level: 3 },
    ],
    interests: ["Marketing & Content", "Business & Management", "Entrepreneurship"],
    projects: ["brand-campaign", "seo-audit"],
    whyTemplate:
      "Your {interest} interest is the core of growth roles; degree branch matters less than a portfolio of campaigns.",
    roadmap: [
      {
        id: "rm-dm-1",
        title: "Marketing Fundamentals",
        duration: "3 weeks",
        goals: ["Funnels, positioning, audiences"],
        tasks: ["Marketing 101 course", "Study 10 great campaigns", "Personal brand setup (LinkedIn)"],
        projects: ["Content calendar for a niche page"],
      },
      {
        id: "rm-dm-2",
        title: "SEO & Content",
        duration: "4 weeks",
        goals: ["Rank content on Google"],
        tasks: ["Keyword research", "On-page SEO", "Write 5 SEO articles"],
        projects: ["seo-audit"],
      },
      {
        id: "rm-dm-3",
        title: "Paid Ads & Analytics",
        duration: "4 weeks",
        goals: ["Spend wisely, measure everything"],
        tasks: ["Google/Meta ads basics", "GA4 + UTM tracking", "A/B test creatives"],
        projects: ["brand-campaign"],
      },
      {
        id: "rm-dm-4",
        title: "Growth Portfolio",
        duration: "3 weeks",
        goals: ["Prove impact with numbers"],
        tasks: ["Run a real campaign (even small budget)", "Document metrics & learnings", "Certifications (Google, HubSpot)"],
        projects: ["Growth case study with before/after metrics"],
      },
    ],
  },
  {
    id: "fintech-analyst",
    title: "FinTech / Financial Analyst",
    family: "Business",
    tagline: "Finance meets data: analysis, risk and products.",
    degrees: ["B.Com", "BBA", "BA", "B.Sc", "B.Tech"],
    branches: ["Other", "CSE", "IT"],
    openToAllBranches: true,
    demand: "Growing",
    avgSalaryLPA: "6–18 LPA",
    requiredSkills: [
      { name: "Financial Accounting", weight: 3, level: 4 },
      { name: "Excel & Sheets", weight: 3, level: 4 },
      { name: "SQL", weight: 2, level: 3 },
      { name: "Statistics", weight: 2, level: 3 },
      { name: "Python", weight: 1, level: 3 },
      { name: "Business Domain", weight: 2, level: 3 },
    ],
    interests: ["Finance & Fintech", "Data & Analytics", "Business & Management"],
    projects: ["stock-dashboard", "expense-analyzer"],
    whyTemplate:
      "Your {interest} interest aligns with finance; analytics skills give you an edge over pure-finance peers.",
    roadmap: [
      {
        id: "rm-fin-1",
        title: "Accounting & Finance Core",
        duration: "4 weeks",
        goals: ["Read financial statements"],
        tasks: ["Balance sheet, P&L, cash flow", "Ratio analysis", "Financial markets basics"],
        projects: ["Company analysis report"],
      },
      {
        id: "rm-fin-2",
        title: "Excel Modeling",
        duration: "3 weeks",
        goals: ["Build 3-statement models"],
        tasks: ["Forecasting models", "DCF basics", "Sensitivity analysis"],
        projects: ["Startup valuation model"],
      },
      {
        id: "rm-fin-3",
        title: "Data Skills",
        duration: "4 weeks",
        goals: ["Analyst-grade tooling"],
        tasks: ["SQL for finance data", "Python/Pandas basics", "Power BI dashboard"],
        projects: ["stock-dashboard"],
      },
      {
        id: "rm-fin-4",
        title: "Certifications & Internships",
        duration: "4 weeks",
        goals: ["Credibility + experience"],
        tasks: ["NISM / CFA L1 prep (optional)", "Apply to fintech internships", "Mock finance interviews"],
        projects: ["Fintech product teardown writeup"],
      },
    ],
  },
  {
    id: "embedded-iot",
    title: "Embedded / IoT Engineer",
    family: "Core Engineering",
    tagline: "Firmware, sensors and connected devices.",
    degrees: ["B.Tech", "B.E."],
    branches: ["ECE", "EEE", "Mechatronics", "Robotics", "Other"],
    openToAllBranches: false,
    demand: "High",
    avgSalaryLPA: "5–16 LPA",
    requiredSkills: [
      { name: "C / Embedded C", weight: 3, level: 4 },
      { name: "Microcontrollers", weight: 3, level: 4 },
      { name: "Circuit Design", weight: 2, level: 3 },
      { name: "Python", weight: 1, level: 3 },
      { name: "RTOS", weight: 1, level: 3 },
      { name: "Communication Protocols", weight: 2, level: 3 },
    ],
    interests: ["Hardware & Electronics", "Core Engineering", "Software & Coding"],
    projects: ["smart-home-iot", "line-follower"],
    whyTemplate:
      "Direct fit for your {branch} branch and {interest} interest; hardware-software boundary roles are growing.",
    roadmap: [
      {
        id: "rm-emb-1",
        title: "C Programming",
        duration: "4 weeks",
        goals: ["Solid C fundamentals"],
        tasks: ["Pointers & memory", "Bit manipulation", "50 practice programs"],
        projects: ["Console-based utility in C"],
      },
      {
        id: "rm-emb-2",
        title: "Microcontrollers",
        duration: "5 weeks",
        goals: ["Blink to build"],
        tasks: ["Arduino / ESP32 basics", "GPIO, PWM, ADC", "I2C & SPI protocols"],
        projects: ["line-follower"],
      },
      {
        id: "rm-emb-3",
        title: "IoT Stack",
        duration: "5 weeks",
        goals: ["Connected devices end-to-end"],
        tasks: ["MQTT & HTTP", "Sensors & calibration", "Simple cloud dashboard"],
        projects: ["smart-home-iot"],
      },
      {
        id: "rm-emb-4",
        title: "Advanced Embedded",
        duration: "4 weeks",
        goals: ["Industry-grade skills"],
        tasks: ["FreeRTOS tasks & queues", "Low-power design", "PCB design basics"],
        projects: ["Battery-powered sensor node"],
      },
    ],
  },
  {
    id: "design-engineer",
    title: "Design / CAD Engineer",
    family: "Core Engineering",
    tagline: "Design, simulate and iterate physical products.",
    degrees: ["B.Tech", "B.E."],
    branches: ["Mechanical", "Automobile", "Aerospace", "Mechatronics", "Civil"],
    openToAllBranches: false,
    demand: "Stable",
    avgSalaryLPA: "4–12 LPA",
    requiredSkills: [
      { name: "CAD (SolidWorks/CATIA)", weight: 3, level: 4 },
      { name: "FEA / Simulation", weight: 2, level: 3 },
      { name: "Engineering Drawing", weight: 2, level: 4 },
      { name: "Manufacturing Processes", weight: 2, level: 3 },
      { name: "MATLAB", weight: 1, level: 3 },
      { name: "GD&T", weight: 1, level: 3 },
    ],
    interests: ["Core Engineering", "Design & UX", "Research"],
    projects: ["gokart-chassis", "hvac-simulation"],
    whyTemplate:
      "Core {branch} career matching your {interest} interest; simulation + design portfolios win here.",
    roadmap: [
      {
        id: "rm-de-1",
        title: "CAD Fundamentals",
        duration: "4 weeks",
        goals: ["Model real parts confidently"],
        tasks: ["SolidWorks/Fusion 360 sketches", "Part & assembly modeling", "Engineering drawing standards"],
        projects: ["Scale model of a machine part"],
      },
      {
        id: "rm-de-2",
        title: "Simulation & FEA",
        duration: "4 weeks",
        goals: ["Validate designs virtually"],
        tasks: ["Static structural analysis", "Thermal analysis basics", "Interpret stress results"],
        projects: ["hvac-simulation"],
      },
      {
        id: "rm-de-3",
        title: "Manufacturing & Materials",
        duration: "3 weeks",
        goals: ["Design for manufacturing"],
        tasks: ["Machining & 3D printing", "Material selection", "Tolerances & GD&T"],
        projects: ["Design-for-3D-printing project"],
      },
      {
        id: "rm-de-4",
        title: "Flagship Project",
        duration: "6 weeks",
        goals: ["A build that impresses at interviews"],
        tasks: ["Join a team (SAE/BAJA/Formula)", "Document design decisions", "Prepare a design portfolio"],
        projects: ["gokart-chassis"],
      },
    ],
  },
  {
    id: "civil-structural",
    title: "Structural / Civil Design Engineer",
    family: "Core Engineering",
    tagline: "Analyze and design safe, efficient structures.",
    degrees: ["B.Tech", "B.E."],
    branches: ["Civil"],
    openToAllBranches: false,
    demand: "Stable",
    avgSalaryLPA: "4–10 LPA",
    requiredSkills: [
      { name: "Structural Analysis", weight: 3, level: 4 },
      { name: "STAAD Pro / ETABS", weight: 3, level: 4 },
      { name: "Concrete & Steel Design", weight: 2, level: 4 },
      { name: "AutoCAD", weight: 2, level: 3 },
      { name: "Estimation & Costing", weight: 1, level: 3 },
      { name: "Site Supervision", weight: 1, level: 2 },
    ],
    interests: ["Core Engineering", "Research"],
    projects: ["building-analysis", "site-report"],
    whyTemplate:
      "The core path for Civil; your {interest} interest in building real structures fits directly.",
    roadmap: [
      {
        id: "rm-civ-1",
        title: "Core Software",
        duration: "4 weeks",
        goals: ["STAAD/ETABS fluency"],
        tasks: ["Model a G+3 building", "Load calculations (IS 875)", "Basic seismic design (IS 1893)"],
        projects: ["building-analysis"],
      },
      {
        id: "rm-civ-2",
        title: "Design Codes",
        duration: "4 weeks",
        goals: ["Design to IS codes"],
        tasks: ["IS 456 RCC design", "Steel design basics (IS 800)", "Foundation design"],
        projects: ["Design report with drawings"],
      },
      {
        id: "rm-civ-3",
        title: "Detailing & Estimation",
        duration: "3 weeks",
        goals: ["From design to site"],
        tasks: ["AutoCAD detailing", "Bar bending schedules", "Quantity estimation & costing"],
        projects: ["site-report"],
      },
      {
        id: "rm-civ-4",
        title: "Internship & Portfolio",
        duration: "4 weeks",
        goals: ["Site + design exposure"],
        tasks: ["Apply to design firms & L&T-type recruiters", "Portfolio of 2 analysis projects", "GATE prep (optional)"],
        projects: ["Complete design portfolio PDF"],
      },
    ],
  },
  {
    id: "biotech-ra",
    title: "Biotech Research / Bioinformatics",
    family: "Science",
    tagline: "Lab science meets data: research and analysis roles.",
    degrees: ["B.Tech", "B.E.", "B.Sc"],
    branches: ["Biotechnology", "Biomedical", "Other"],
    openToAllBranches: false,
    demand: "Growing",
    avgSalaryLPA: "4–12 LPA",
    requiredSkills: [
      { name: "Molecular Biology", weight: 3, level: 4 },
      { name: "Lab Techniques", weight: 2, level: 4 },
      { name: "Python", weight: 2, level: 3 },
      { name: "Bioinformatics Tools", weight: 2, level: 3 },
      { name: "Statistics", weight: 2, level: 3 },
      { name: "Scientific Writing", weight: 1, level: 3 },
    ],
    interests: ["Healthcare & Biology", "Research", "Data & Analytics"],
    projects: ["genomics-analysis", "lab-portfolio"],
    whyTemplate:
      "Combines your {branch} foundation with {interest}; data skills differentiate you in bio roles.",
    roadmap: [
      {
        id: "rm-bio-1",
        title: "Core Biology Strength",
        duration: "4 weeks",
        goals: ["Solid molecular biology base"],
        tasks: ["Genetics & cell biology revision", "Lab technique certifications", "Read 10 review papers"],
        projects: ["Literature review document"],
      },
      {
        id: "rm-bio-2",
        title: "Bioinformatics Basics",
        duration: "4 weeks",
        goals: ["Analyze biological data"],
        tasks: ["NCBI & BLAST", "Python for biology (Biopython)", "Sequence analysis"],
        projects: ["genomics-analysis"],
      },
      {
        id: "rm-bio-3",
        title: "Research Experience",
        duration: "6 weeks",
        goals: ["Lab or dry-lab project"],
        tasks: ["Summer research fellowship applications", "Contribute to a lab project", "Poster/paper submission"],
        projects: ["lab-portfolio"],
      },
      {
        id: "rm-bio-4",
        title: "Career Track Selection",
        duration: "3 weeks",
        goals: ["Industry vs academia decision"],
        tasks: ["Industry internship applications", "GATE/JAM/GRE prep (optional)", "Scientific writing practice"],
        projects: ["Statement of purpose draft"],
      },
    ],
  },
  {
    id: "ux-designer",
    title: "UX / Product Designer",
    family: "Design",
    tagline: "Design interfaces and experiences people love.",
    degrees: ["BA", "B.Sc", "B.Tech", "B.E.", "BCA", "BBA"],
    branches: ["Other", "CSE", "IT", "Mechanical"],
    openToAllBranches: true,
    demand: "Growing",
    avgSalaryLPA: "5–15 LPA",
    requiredSkills: [
      { name: "Figma & Design Tools", weight: 3, level: 4 },
      { name: "User Research", weight: 2, level: 3 },
      { name: "Prototyping", weight: 2, level: 4 },
      { name: "Visual Design", weight: 2, level: 4 },
      { name: "HTML/CSS Basics", weight: 1, level: 2 },
      { name: "Communication", weight: 1, level: 3 },
    ],
    interests: ["Design & UX", "Software & Coding", "Marketing & Content"],
    projects: ["app-redesign", "ux-case-study"],
    whyTemplate:
      "Your {interest} interest and eye for design fit this portfolio-first career — branch doesn't matter.",
    roadmap: [
      {
        id: "rm-ux-1",
        title: "Design Fundamentals",
        duration: "3 weeks",
        goals: ["Learn to see"],
        tasks: ["Typography, color, layout", "Copy 5 great screens", "Figma basics"],
        projects: ["Redesign a bad app screen"],
      },
      {
        id: "rm-ux-2",
        title: "UX Process",
        duration: "4 weeks",
        goals: ["Research to wireframes"],
        tasks: ["User interviews", "Personas & journey maps", "Wireframing"],
        projects: ["ux-case-study"],
      },
      {
        id: "rm-ux-3",
        title: "High-Fidelity Design",
        duration: "4 weeks",
        goals: ["Beautiful, usable UI"],
        tasks: ["Design systems", "Interactive prototypes", "Micro-interactions"],
        projects: ["app-redesign"],
      },
      {
        id: "rm-ux-4",
        title: "Portfolio & Networking",
        duration: "3 weeks",
        goals: ["Get hired from your portfolio"],
        tasks: ["3 full case studies", "Behance/Dribbble presence", "Design community participation"],
        projects: ["Portfolio website"],
      },
    ],
  },
  {
    id: "hr-analyst",
    title: "HR / People Analytics",
    family: "Business",
    tagline: "Data-driven people management.",
    degrees: ["BBA", "B.Com", "BA", "B.Sc"],
    branches: ["Other", "CSE", "IT"],
    openToAllBranches: true,
    demand: "Stable",
    avgSalaryLPA: "4–10 LPA",
    requiredSkills: [
      { name: "Communication", weight: 3, level: 4 },
      { name: "Excel & Sheets", weight: 2, level: 4 },
      { name: "HR Fundamentals", weight: 2, level: 3 },
      { name: "Data Visualization", weight: 1, level: 3 },
      { name: "Statistics", weight: 1, level: 3 },
      { name: "Business Domain", weight: 1, level: 3 },
    ],
    interests: ["Business & Management", "Teaching & Training", "Data & Analytics"],
    projects: ["hr-analytics", "engagement-survey"],
    whyTemplate:
      "People + data is a growing niche; your {interest} interest suits the stakeholder-heavy nature of HR.",
    roadmap: [
      {
        id: "rm-hr-1",
        title: "HR Foundations",
        duration: "3 weeks",
        goals: ["Core HR processes"],
        tasks: ["Recruitment & onboarding flow", "HRIS tools overview", "Labour law basics"],
        projects: ["Recruitment process map"],
      },
      {
        id: "rm-hr-2",
        title: "People Analytics",
        duration: "4 weeks",
        goals: ["Measure what matters"],
        tasks: ["Attrition & engagement metrics", "Excel dashboards", "Survey design"],
        projects: ["hr-analytics"],
      },
      {
        id: "rm-hr-3",
        title: "Practical Experience",
        duration: "4 weeks",
        goals: ["Real HR exposure"],
        tasks: ["Campus club HR role", "LinkedIn recruiting practice", "SHRM/related certification"],
        projects: ["engagement-survey"],
      },
    ],
  },
];

export const PROJECTS: ProjectRec[] = [
  {
    id: "ml-endtoend",
    name: "End-to-End ML Model with Deployment",
    difficulty: "Intermediate",
    technologies: ["Python", "Scikit-learn", "FastAPI", "Docker"],
    skills: ["Machine Learning", "Python", "Docker & Cloud"],
    why: "The single project interviewers trust most: data to deployed API.",
    careers: ["ml-engineer", "data-scientist"],
    outcome: "A live API that serves predictions",
    steps: [
      "Pick a public dataset (Kaggle)",
      "EDA + feature engineering notebook",
      "Train and compare 3 models",
      "Wrap in FastAPI",
      "Dockerize and deploy (Render/Railway)",
    ],
  },
  {
    id: "nlp-sentiment",
    name: "Sentiment Analysis of Product Reviews",
    difficulty: "Intermediate",
    technologies: ["Python", "NLP", "Transformers"],
    skills: ["Deep Learning", "Python", "Machine Learning"],
    why: "Shows you can handle text data and modern transformer models.",
    careers: ["ml-engineer", "ai-engineer"],
    outcome: "A fine-tuned model with a demo notebook",
    steps: [
      "Scrape or download reviews dataset",
      "Clean + tokenize text",
      "Fine-tune a small BERT variant",
      "Evaluate with confusion matrix",
      "Build a Gradio demo",
    ],
  },
  {
    id: "cv-defect",
    name: "Defect Detection from Images (Computer Vision)",
    difficulty: "Advanced",
    technologies: ["Python", "OpenCV", "PyTorch"],
    skills: ["Deep Learning", "Python", "Machine Learning"],
    why: "Industry-relevant CV problem (manufacturing QC) — great for core + AI crossover.",
    careers: ["ml-engineer", "ai-engineer"],
    outcome: "Trained detector with metrics report",
    steps: [
      "Source defect dataset (e.g., casting product images)",
      "Augment limited data",
      "Train CNN / use transfer learning",
      "Add explainability (Grad-CAM)",
      "Write a results report",
    ],
  },
  {
    id: "rag-tutor",
    name: "RAG Study Assistant (Chat with Your Notes)",
    difficulty: "Intermediate",
    technologies: ["Python", "LangChain", "Vector DB", "Next.js"],
    skills: ["LLM APIs & RAG", "Prompt Engineering", "Web Development"],
    why: "The most in-demand GenAI pattern; perfect hackathon project too.",
    careers: ["ai-engineer", "ml-engineer"],
    outcome: "Working chat app grounded on your PDFs",
    steps: [
      "Parse PDFs into chunks",
      "Embed + store in a vector DB",
      "Retrieval + LLM answer pipeline",
      "Simple Next.js chat UI",
      "Add evaluation questions",
    ],
  },
  {
    id: "career-agent",
    name: "AI Career Agent (Like This App!)",
    difficulty: "Advanced",
    technologies: ["Next.js", "Python", "LLM APIs"],
    skills: ["LLM APIs & RAG", "Web Development", "Prompt Engineering"],
    why: "Meta-project: demonstrates product thinking + AI integration in one.",
    careers: ["ai-engineer", "fullstack-dev"],
    outcome: "Deployed AI product you can demo live",
    steps: [
      "Design agent workflow (assess → recommend → coach)",
      "Implement matching logic",
      "Add LLM chat with profile context",
      "Deploy with auth",
      "Record a 2-minute demo",
    ],
  },
  {
    id: "sales-forecast",
    name: "Retail Sales Forecasting Dashboard",
    difficulty: "Intermediate",
    technologies: ["Python", "Pandas", "Prophet", "Power BI"],
    skills: ["Machine Learning", "Data Visualization", "SQL"],
    why: "Time-series + business framing — classic data science interview material.",
    careers: ["data-scientist", "data-analyst"],
    outcome: "Forecast model + executive dashboard",
    steps: [
      "Get retail sales dataset",
      "Explore seasonality & trends",
      "Train Prophet/ARIMA model",
      "Build Power BI dashboard",
      "Write business recommendations",
    ],
  },
  {
    id: "ab-test-suite",
    name: "A/B Test Analysis Suite",
    difficulty: "Beginner",
    technologies: ["Python", "Statistics", "Streamlit"],
    skills: ["Statistics", "Python", "Business Domain"],
    why: "Proves you understand experimentation — asked in almost every DS interview.",
    careers: ["data-scientist", "data-analyst", "fintech-analyst"],
    outcome: "Streamlit app that analyzes any A/B test CSV",
    steps: [
      "Learn hypothesis testing basics",
      "Implement power analysis",
      "Build Streamlit upload + analysis flow",
      "Visualize distributions & confidence intervals",
      "Auto-generate conclusion text",
    ],
  },
  {
    id: "covid-dashboard",
    name: "Public Health Data Dashboard",
    difficulty: "Beginner",
    technologies: ["SQL", "Power BI", "Excel"],
    skills: ["Data Visualization", "SQL", "Excel & Sheets"],
    why: "Low-barrier first dashboard that teaches cleaning, joins and storytelling.",
    careers: ["data-analyst", "data-scientist"],
    outcome: "Interactive dashboard on public data",
    steps: [
      "Download public health dataset",
      "Clean in Excel/SQL",
      "Model tables in Power BI",
      "Design 3-page report",
      "Publish & share link",
    ],
  },
  {
    id: "hr-analytics",
    name: "Employee Attrition Analysis",
    difficulty: "Beginner",
    technologies: ["Python", "Pandas", "Seaborn"],
    skills: ["Statistics", "Python", "Data Visualization"],
    why: "People analytics is a hot niche; simple dataset, deep insights possible.",
    careers: ["data-analyst", "hr-analyst"],
    outcome: "Analysis notebook + insights deck",
    steps: [
      "Use IBM HR attrition dataset",
      "EDA on attrition drivers",
      "Logistic regression for interpretability",
      "Create insights one-pager",
      "Present to a peer group",
    ],
  },
  {
    id: "engagement-survey",
    name: "Student Engagement Survey Study",
    difficulty: "Beginner",
    technologies: ["Google Forms", "Excel", "Statistics"],
    skills: ["HR Fundamentals", "Statistics", "Communication"],
    why: "Run a real survey end-to-end — methodology experience beats theory.",
    careers: ["hr-analyst", "digital-marketer"],
    outcome: "Survey report with actionable findings",
    steps: [
      "Design questionnaire (10-12 items)",
      "Collect 100+ responses on campus",
      "Analyze in Excel",
      "Write findings & recommendations",
      "Share with a student body/club",
    ],
  },
  {
    id: "stock-dashboard",
    name: "Stock Portfolio Tracker & Analyzer",
    difficulty: "Intermediate",
    technologies: ["Python", "yfinance", "Streamlit"],
    skills: ["Python", "Excel & Sheets", "Statistics"],
    why: "Finance + coding crossover that makes your resume stand out for fintech roles.",
    careers: ["fintech-analyst", "data-analyst"],
    outcome: "Live tracker with risk metrics",
    steps: [
      "Pull data with yfinance",
      "Compute returns, volatility, Sharpe",
      "Build Streamlit UI",
      "Add comparison against NIFTY",
      "Deploy on Streamlit Cloud",
    ],
  },
  {
    id: "expense-analyzer",
    name: "Personal Finance Expense Analyzer",
    difficulty: "Beginner",
    technologies: ["Excel", "Python", "Pandas"],
    skills: ["Excel & Sheets", "Python", "Financial Accounting"],
    why: "Practical first project for commerce students entering analytics.",
    careers: ["fintech-analyst", "data-analyst"],
    outcome: "Automated monthly expense report",
    steps: [
      "Export bank statement CSV",
      "Categorize transactions",
      "Monthly spend trends",
      "Budget vs actual chart",
      "Automate with a script",
    ],
  },
  {
    id: "brand-campaign",
    name: "Full Digital Campaign for a Local Brand",
    difficulty: "Intermediate",
    technologies: ["Meta Ads", "Google Analytics", "Canva"],
    skills: ["Social Media", "Marketing Analytics", "Copywriting"],
    why: "Real spend, real metrics — the portfolio piece marketing hiring managers respect.",
    careers: ["digital-marketer"],
    outcome: "Campaign with documented ROI",
    steps: [
      "Find a local business to help",
      "Define audience & offer",
      "Create creatives & copy",
      "Run small-budget campaign (₹2-5k)",
      "Report metrics & learnings",
    ],
  },
  {
    id: "seo-audit",
    name: "SEO Audit & Content Plan for a Website",
    difficulty: "Beginner",
    technologies: ["Ahrefs/Semrush", "Google Search Console", "Sheets"],
    skills: ["SEO & Content", "Marketing Analytics"],
    why: "Shows structured thinking; every company needs this.",
    careers: ["digital-marketer"],
    outcome: "Audit document + 3-month content calendar",
    steps: [
      "Pick any real website",
      "Technical SEO checklist",
      "Keyword gap analysis",
      "Competitor benchmark",
      "Present prioritized action plan",
    ],
  },
  {
    id: "smart-home-iot",
    name: "Smart Home Automation Hub",
    difficulty: "Intermediate",
    technologies: ["ESP32", "MQTT", "Node-RED"],
    skills: ["Microcontrollers", "Communication Protocols", "Python"],
    why: "Classic IoT stack demonstration — hardware + software + cloud.",
    careers: ["embedded-iot"],
    outcome: "Working prototype controlling real devices",
    steps: [
      "Wire relays & sensors to ESP32",
      "MQTT broker setup",
      "Node-RED dashboard",
      "Mobile control flow",
      "Enclosure & final build",
    ],
  },
  {
    id: "line-follower",
    name: "Line Follower Robot",
    difficulty: "Beginner",
    technologies: ["Arduino", "C++", "IR Sensors"],
    skills: ["Microcontrollers", "C / Embedded C", "Circuit Design"],
    why: "The perfect first embedded project — hardware debugging lessons for life.",
    careers: ["embedded-iot", "design-engineer"],
    outcome: "Tuned robot completing a track",
    steps: [
      "Assemble chassis & sensors",
      "Basic motor control code",
      "Add PID line following",
      "Tune for speed",
      "Race documentation",
    ],
  },
  {
    id: "gokart-chassis",
    name: "SAE BAJA / Go-Kart Chassis Design",
    difficulty: "Advanced",
    technologies: ["SolidWorks", "ANSYS", "Welding"],
    skills: ["CAD (SolidWorks/CATIA)", "FEA / Simulation", "Manufacturing Processes"],
    why: "Team flagship projects dominate core-engineer interviews.",
    careers: ["design-engineer"],
    outcome: "Manufactured, tested vehicle system",
    steps: [
      "Join the college SAE team",
      "Own a subsystem (brakes/suspension)",
      "CAD + FEA iterations",
      "Manufacturing support",
      "Competition & documentation",
    ],
  },
  {
    id: "hvac-simulation",
    name: "HVAC Ducting Design & Simulation",
    difficulty: "Intermediate",
    technologies: ["ANSYS Fluent", "Revit MEP", "AutoCAD"],
    skills: ["FEA / Simulation", "CAD (SolidWorks/CATIA)", "Engineering Drawing"],
    why: "Building-services simulation is a reliable placement path for mechanical engineers.",
    careers: ["design-engineer", "civil-structural"],
    outcome: "Simulated design with performance report",
    steps: [
      "Learn HVAC fundamentals",
      "Model duct layout",
      "CFD airflow simulation",
      "Optimize for pressure drop",
      "Prepare BOQ & report",
    ],
  },
  {
    id: "building-analysis",
    name: "G+5 RCC Building Analysis & Design",
    difficulty: "Intermediate",
    technologies: ["STAAD Pro", "ETABS", "AutoCAD"],
    skills: ["Structural Analysis", "STAAD Pro / ETABS", "Concrete & Steel Design"],
    why: "The standard portfolio requirement for structural engineering roles.",
    careers: ["civil-structural"],
    outcome: "Complete design report with drawings",
    steps: [
      "Plan & load calculation",
      "Model in STAAD/ETABS",
      "Design beams & columns",
      "Produce AutoCAD drawings",
      "Compile report",
    ],
  },
  {
    id: "site-report",
    name: "Construction Site Study Report",
    difficulty: "Beginner",
    technologies: ["Site visits", "Excel", "Photography"],
    skills: ["Site Supervision", "Estimation & Costing", "Communication"],
    why: "Site exposure signals practicality to civil recruiters.",
    careers: ["civil-structural"],
    outcome: "Documented site study with photos & learnings",
    steps: [
      "Arrange site visit permission",
      "Observe safety & processes",
      "Interview the site engineer",
      "Document with photos",
      "Present findings",
    ],
  },
  {
    id: "genomics-analysis",
    name: "Genomic Sequence Analysis Pipeline",
    difficulty: "Advanced",
    technologies: ["Python", "Biopython", "Jupyter"],
    skills: ["Bioinformatics Tools", "Python", "Statistics"],
    why: "Dry-lab bio project that demonstrates computational biology skills.",
    careers: ["biotech-ra"],
    outcome: "Notebook pipeline with biological interpretation",
    steps: [
      "Download public genomic data (NCBI)",
      "Sequence alignment with Biopython",
      "Phylogenetic analysis",
      "Visualize results",
      "Interpret findings biologically",
    ],
  },
  {
    id: "lab-portfolio",
    name: "Lab Techniques Portfolio",
    difficulty: "Beginner",
    technologies: ["PCR", "Gel Electrophoresis", "Chromatography"],
    skills: ["Lab Techniques", "Molecular Biology", "Scientific Writing"],
    why: "Documented wet-lab competencies with photos and protocols.",
    careers: ["biotech-ra"],
    outcome: "Structured portfolio of lab skills",
    steps: [
      "List techniques from coursework",
      "Document each protocol",
      "Photograph setups & results",
      "Reflect on learnings",
      "Format as professional PDF",
    ],
  },
  {
    id: "app-redesign",
    name: "Complete App Redesign Case Study",
    difficulty: "Intermediate",
    technologies: ["Figma", "Maze", "Notion"],
    skills: ["Figma & Design Tools", "User Research", "Prototyping"],
    why: "The canonical UX portfolio piece: problem → research → solution → metrics.",
    careers: ["ux-designer"],
    outcome: "Full case study with before/after designs",
    steps: [
      "Pick an app you find frustrating",
      "Heuristic evaluation",
      "User interviews (5 people)",
      "Wireframes → hi-fi mockups",
      "Usability test & iterate",
    ],
  },
  {
    id: "ux-case-study",
    name: "UX Research Case Study",
    difficulty: "Beginner",
    technologies: ["Figma", "Google Forms", "FigJam"],
    skills: ["User Research", "Communication", "Visual Design"],
    why: "Research-first projects differentiate juniors who can only push pixels.",
    careers: ["ux-designer"],
    outcome: "Research report with design recommendations",
    steps: [
      "Define a campus problem",
      "Survey + interview users",
      "Synthesize into personas",
      "Journey map with pain points",
      "Propose & prototype solutions",
    ],
  },
  {
    id: "saas-dashboard",
    name: "Full-Stack SaaS Dashboard",
    difficulty: "Advanced",
    technologies: ["Next.js", "PostgreSQL", "Tailwind"],
    skills: ["Web Development", "Databases & SQL", "Docker & Cloud"],
    why: "Production-grade CRUD app with auth — the strongest SDE portfolio signal.",
    careers: ["fullstack-dev", "ai-engineer"],
    outcome: "Deployed multi-user web application",
    steps: [
      "Design schema & API",
      "Build auth (NextAuth)",
      "CRUD + dashboard UI",
      "Testing & error states",
      "Deploy & write README",
    ],
  },
  {
    id: "ecommerce-api",
    name: "E-Commerce REST API",
    difficulty: "Intermediate",
    technologies: ["Node.js", "Express", "MongoDB"],
    skills: ["Databases & SQL", "Web Development", "JavaScript"],
    why: "Backend fundamentals: auth, payments, pagination, validation.",
    careers: ["fullstack-dev"],
    outcome: "Documented API with Postman collection",
    steps: [
      "Design endpoints & models",
      "Implement auth & roles",
      "Cart + order flow",
      "Validation & error handling",
      "Deploy with docs",
    ],
  },
];

export const ASSESSMENT_QUESTIONS: AssessmentQuestion[] = [
  {
    id: "q1",
    question: "Which activity would you happily do for hours?",
    options: [
      { label: "Building apps or websites", interests: ["Software & Coding", "Design & UX"] },
      { label: "Finding patterns in data", interests: ["Data & Analytics", "AI & Machine Learning"] },
      { label: "Fixing gadgets or circuits", interests: ["Hardware & Electronics", "Core Engineering"] },
      { label: "Planning events or leading teams", interests: ["Business & Management", "Marketing & Content"] },
    ],
  },
  {
    id: "q2",
    question: "A company gives you its failing product data. What do you do first?",
    options: [
      { label: "Dig into the numbers and charts", interests: ["Data & Analytics"], skills: { SQL: 2, "Excel & Sheets": 2 } },
      { label: "Build a tool to automate the analysis", interests: ["Software & Coding"], skills: { Python: 2, JavaScript: 2 } },
      { label: "Interview customers to understand them", interests: ["Marketing & Content", "Design & UX"] },
      { label: "Study competitors and market trends", interests: ["Business & Management", "Entrepreneurship"] },
    ],
  },
  {
    id: "q3",
    question: "Which problem excites you most?",
    options: [
      { label: "Teaching a computer to recognize images", interests: ["AI & Machine Learning", "Research"] },
      { label: "Making a robot navigate a room", interests: ["Hardware & Electronics", "Core Engineering"] },
      { label: "Designing an app screen people love", interests: ["Design & UX"] },
      { label: "Doubling a startup's revenue", interests: ["Business & Management", "Finance & Fintech"] },
    ],
  },
  {
    id: "q4",
    question: "How comfortable are you with math and statistics?",
    options: [
      { label: "Love it — give me equations", interests: ["Research", "AI & Machine Learning"], skills: { Statistics: 3 } },
      { label: "Okay with applied math", interests: ["Data & Analytics", "Finance & Fintech"], skills: { Statistics: 2 } },
      { label: "Prefer avoiding heavy math", interests: ["Marketing & Content", "Design & UX", "Teaching & Training"] },
      { label: "I use it only when needed", interests: ["Software & Coding", "Business & Management"] },
    ],
  },
  {
    id: "q5",
    question: "Pick your ideal first job environment:",
    options: [
      { label: "Startup — fast, chaotic, building", interests: ["Entrepreneurship", "Software & Coding"] },
      { label: "Big tech or MNC — structured, scale", interests: ["Software & Coding", "Data & Analytics"] },
      { label: "Lab or research institute", interests: ["Research", "Healthcare & Biology"] },
      { label: "Field work — sites, factories, clients", interests: ["Core Engineering", "Business & Management"] },
    ],
  },
  {
    id: "q6",
    question: "Which subject did you enjoy most this year?",
    options: [
      { label: "Programming / CS subjects", interests: ["Software & Coding"], skills: { Python: 2, JavaScript: 2 } },
      { label: "Maths / Statistics", interests: ["Data & Analytics", "AI & Machine Learning"], skills: { Statistics: 2 } },
      { label: "Electronics / machines / structures", interests: ["Hardware & Electronics", "Core Engineering"] },
      { label: "Commerce, economics or management", interests: ["Business & Management", "Finance & Fintech"] },
    ],
  },
  {
    id: "q7",
    question: "What does your ideal work output look like?",
    options: [
      { label: "Working software people use", interests: ["Software & Coding", "AI & Machine Learning"] },
      { label: "Reports and dashboards that drive decisions", interests: ["Data & Analytics", "Business & Management"] },
      { label: "Physical products and machines", interests: ["Core Engineering", "Hardware & Electronics"] },
      { label: "Campaigns, content and growth numbers", interests: ["Marketing & Content", "Entrepreneurship"] },
    ],
  },
  {
    id: "q8",
    question: "How do you prefer to learn new skills?",
    options: [
      { label: "Tutorials + courses, step by step", interests: [], skills: {} },
      { label: "Build projects directly, learn by breaking", interests: ["Entrepreneurship", "Software & Coding"], skills: { Python: 1 } },
      { label: "Reading books and research papers", interests: ["Research"] },
      { label: "Group study and discussions", interests: ["Teaching & Training", "Business & Management"] },
    ],
  },
  {
    id: "q9",
    question: "Where do you want to be 5 years after graduation?",
    options: [
      { label: "Senior engineer at a top tech company", interests: ["Software & Coding", "AI & Machine Learning"] },
      { label: "Leading a team or business function", interests: ["Business & Management", "Marketing & Content"] },
      { label: "Running my own company", interests: ["Entrepreneurship", "Finance & Fintech"] },
      { label: "Research / higher studies (MS, PhD)", interests: ["Research", "Healthcare & Biology"] },
    ],
  },
  {
    id: "q10",
    question: "Which of these have you already tried?",
    options: [
      { label: "Python or any programming", interests: ["Software & Coding"], skills: { Python: 2 } },
      { label: "Excel, SQL or dashboards", interests: ["Data & Analytics"], skills: { "Excel & Sheets": 2, SQL: 2 } },
      { label: "Arduino, circuits or workshop tools", interests: ["Hardware & Electronics"], skills: { "Circuit Design": 2 } },
      { label: "Content creation or managing social media", interests: ["Marketing & Content"], skills: { "Social Media": 2 } },
    ],
  },
];

export function buildDemoProfile(): StudentProfile {
  const now = new Date().toISOString();
  return {
    id: "demo-student",
    name: "Ananya Sharma",
    email: "ananya.sharma@demo.edu",
    degree: "B.Tech",
    branch: "AIML",
    college: "JNTU Hyderabad",
    gradYear: 2027,
    interests: ["AI & Machine Learning", "Data & Analytics", "Software & Coding"],
    skills: {
      Python: 3,
      SQL: 3,
      Statistics: 2,
      "Machine Learning": 1,
      "Deep Learning": 1,
      "Web Development": 2,
      "Excel & Sheets": 3,
      "Git & GitHub": 2,
      Communication: 3,
      "Docker & Cloud": 1,
    },
    targetCareerId: null,
    onboarded: true,
    language: "en",
    createdAt: now,
  };
}
